/** Wipe all uniform state (initial uniforms and shaderAnimations) */
export const CHANGE_SHADER = 'CHANGE_SHADER'
export const SET_SHADER_NAME = 'SET_SHADER_NAME'
export const SET_ANIMATION_NAME = 'SET_ANIMATION_NAME'

// Initial state
export const SET_INITIAL_ANIMATION_STATE = 'SET_INITIAL_ANIMATION_STATE'
export const UPDATE_INITIAL_TRANSLATION = 'UPDATE_INITIAL_TRANSLATION'
export const UPDATE_INITIAL_ROTATION = 'UPDATE_INITIAL_ROTATION'
export const UPDATE_INITIAL_SCALE = 'UPDATE_INITIAL_SCALE'
export const UPDATE_INITIAL_COLOR = 'UPDATE_INITIAL_COLOR'
export const UPDATE_INITIAL_UNIFORMS = 'UPDATE_INITIAL_UNIFORMS'

// Model animations
export const SET_ANIMATIONS = 'SET_ANIMATIONS'
export const ADD_ANIMATION = 'ADD_ANIMATION'
export const CLEAN_ANIMATIONS = 'CLEAN_ANIMATIONS'
export const REMOVE_ANIMATION = 'REMOVE_ANIMATION'
export const UPDATE_ANIMATION = 'UPDATE_ANIMATION'

// Shader animations (animate uniforms)
export const SET_SHADER_ANIMATIONS = 'SET_SHADER_ANIMATIONS'
export const ADD_SHADER_ANIMATION = 'ADD_SHADER_ANIMATION'
export const CLEAN_SHADER_ANIMATIONS = 'CLEAN_SHADER_ANIMATIONS'
export const REMOVE_SHADER_ANIMATION = 'REMOVE_SHADER_ANIMATION'
export const UPDATE_SHADER_ANIMATION = 'UPDATE_SHADER_ANIMATION'